---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/finalizers
  - clusters/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: argocd
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
